var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                                 xx!xx          ",
   "                                    o o                          x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxxxxx                       xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o  xx                            x  ",
   "  x                                                                          x  ",
   "  x                                      xxxxx                             y x  ",
   "  x                                  xx                                      x  ",
   "  x  @                                                                       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x     x   x          ",
   "                              x!!!x                  x!!!!!x     x!!!x          ",
   "                              x!!!x                  x!!!!!x     x!!!x          ",
   "                              xxxxx                  xxxxxxx     xxxxx          ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                                 xx!xx          ",
   "                                                                 x!!!x          ",
   "                                                                 x!!!x          ",
   "                                                                 xv!vx          ",
   "                                  o     o                        x v x      xx  ",
   "  xx                        o     xx    xx                                   x  ",
   "  x                        xxxx                                              x  ",
   "  x                                                   o       o            y x  ",
   "  x          xxxxxxxxxxx                             xxxxx    xx             x  ",
   "  x  @      xx         xx                        xxxxx                       x  ",
   "  xxxxx    xx           xx                   xxxxx               x   xxxxxxxxx  ",
   "                                                                                ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                            xx  ",
    "  xx                 o   o  ooo  o   o  o  o  o                              x  ",
    "  x                   o o  o   o  o o   o  o  o                              x  ",
    "  x                    o   ooooo   o                                       y x  ",
    "  x                    o   o   o   o    o  o  o                              x  ",
    "  x  @                                                                       x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                ",
    "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
    "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
